version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: Halden_1
    restart: always
    ports:
      - "28000:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Halden
    volumes:
      - Halden_data_1:/data/db

volumes:
  Halden_data_1:
